@@ -19,7 +19,9 @@ 
 dist:
    rm -rf "dist/clfs-embedded-bootscripts-$(VERSION)"

 create-dirs:
-     install -d -m ${DIRMODE} ${EXTDIR}/rc.d/{init.d,start,stop}
+     install -d -m ${DIRMODE} ${EXTDIR}/rc.d/init.d
+     install -d -m ${DIRMODE} ${EXTDIR}/rc.d/start
+     install -d -m ${DIRMODE} ${EXTDIR}/rc.d/stop

 install-bootscripts: create-dirs
	install -m ${CONFMODE} clfs/rc.d/init.d/functions ${EXTDIR}/rc.d/init.d/
